[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = '0.8.20'
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 4294967295
via_ir = true
bytecode_hash = 'none'

verbosity = 2

[fuzz]
runs = 65536
seed = 42
dictionary_weight = 0
include_storage = false
include_push_bytes = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
